=== berezovskyi/ldp4j/framework/application/persistency/src/test/resources/database-schema.dtd
<!--

    #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
      This file is part of the LDP4j Project:
        http://www.ldp4j.org/

      Center for Open Middleware
        http://www.centeropenmiddleware.com/
    #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
      Copyright (C) 2014 Center for Open Middleware.
    #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
      Licensed under the Apache License, Version 2.0 (the "License");
      you may not use this file except in compliance with the License.
      You may obtain a copy of the License at

                http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.
    #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
      Artifact    : org.ldp4j.framework:ldp4j-application-persistency:1.0.0-SNAPSHOT
      Bundle      : ldp4j-application-persistency-1.0.0-SNAPSHOT.jar
    #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#

-->
<!ELEMENT dataset ((Application*, Endpoint*, Template* , TemplateAttachment* , RDFSourceTemplate* , BasicContainerTemplate*, DirectContainerTemplate* , IndirectContainerTemplate* , Resource* , ResourceAttachment* , RDFSource* , Container*, MembershipAwareContainer* , Slug* , Failure*))>
<!ELEMENT Application EMPTY>
<!ATTLIST Application
	path CDATA #REQUIRED
	name CDATA #REQUIRED
	description CDATA #IMPLIED
>

<!ELEMENT Template EMPTY>
<!ATTLIST Template
	template_id CDATA #REQUIRED
	handlerClassName CDATA #REQUIRED
	name CDATA #REQUIRED
	description CDATA #IMPLIED
	app_path CDATA #REQUIRED
>

<!ELEMENT TemplateAttachment EMPTY>
<!ATTLIST TemplateAttachment
	attachment_id CDATA #REQUIRED
	name CDATA #REQUIRED
	description CDATA #IMPLIED
	predicate CDATA #IMPLIED
	path CDATA #REQUIRED
	owner_template_id CDATA #REQUIRED
	attached_template_id CDATA #REQUIRED
>

<!ELEMENT RDFSourceTemplate EMPTY>
<!ATTLIST RDFSourceTemplate
	template_id CDATA #REQUIRED
>

<!ELEMENT BasicContainerTemplate EMPTY>
<!ATTLIST BasicContainerTemplate
	template_id CDATA #REQUIRED
	member_template_id CDATA #REQUIRED
>

<!ELEMENT DirectContainerTemplate EMPTY>
<!ATTLIST DirectContainerTemplate
	template_id CDATA #REQUIRED
	member_template_id CDATA #REQUIRED
	membershipPredicate CDATA #REQUIRED
	membershipRelation CDATA #REQUIRED
>

<!ELEMENT IndirectContainerTemplate EMPTY>
<!ATTLIST IndirectContainerTemplate
	template_id CDATA #REQUIRED
	member_template_id CDATA #REQUIRED
	membershipPredicate CDATA #REQUIRED
	membershipRelation CDATA #REQUIRED
	insertedContentRelation CDATA #REQUIRED
>

<!ELEMENT Resource EMPTY>
<!ATTLIST Resource
	resource_id CDATA #REQUIRED
	businessKey CDATA #REQUIRED
	indirect_id CDATA #IMPLIED
	template_id CDATA #REQUIRED
	endpoint_id CDATA #REQUIRED
	container_id CDATA #IMPLIED
>

<!ELEMENT ResourceAttachment EMPTY>
<!ATTLIST ResourceAttachment
	attachment_id CDATA #REQUIRED
	template_attachment_id CDATA #REQUIRED
	owner_resource_id CDATA #REQUIRED
	attached_resource_id CDATA #REQUIRED
	version CDATA #REQUIRED
>

<!ELEMENT RDFSource EMPTY>
<!ATTLIST RDFSource
	resource_id CDATA #REQUIRED
>

<!ELEMENT Container EMPTY>
<!ATTLIST Container
	resource_id CDATA #REQUIRED
	memberCount CDATA #REQUIRED
>

<!ELEMENT MembershipAwareContainer EMPTY>
<!ATTLIST MembershipAwareContainer
	resource_id CDATA #REQUIRED
	target_resource_id CDATA #REQUIRED
	memberCount CDATA #REQUIRED
>

<!ELEMENT Slug EMPTY>
<!ATTLIST Slug
	resource_id CDATA #REQUIRED
	path CDATA #REQUIRED
	version CDATA #REQUIRED
>

<!ELEMENT Endpoint EMPTY>
<!ATTLIST Endpoint
	endpoint_id CDATA #REQUIRED
	path CDATA #REQUIRED
	created CDATA #REQUIRED
	deleted CDATA #IMPLIED
	entityTag CDATA #REQUIRED
	modified CDATA #REQUIRED
	app_path CDATA #REQUIRED
>

<!ELEMENT Failure EMPTY>
<!ATTLIST Failure
	failure_id CDATA #REQUIRED
	message CDATA #REQUIRED
	ocurredOn CDATA #REQUIRED
	request CDATA #REQUIRED
	endpoint_id CDATA #REQUIRED
>

=== berezovskyi/ldp4j/framework/application/persistency/src/test/resources/custom-application.xml
<!--

    #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
      This file is part of the LDP4j Project:
        http://www.ldp4j.org/

      Center for Open Middleware
        http://www.centeropenmiddleware.com/
    #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
      Copyright (C) 2014 Center for Open Middleware.
    #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
      Licensed under the Apache License, Version 2.0 (the "License");
      you may not use this file except in compliance with the License.
      You may obtain a copy of the License at

                http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.
    #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
      Artifact    : org.ldp4j.framework:ldp4j-application-persistency:1.0.0-SNAPSHOT
      Bundle      : ldp4j-application-persistency-1.0.0-SNAPSHOT.jar
    #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#

-->
<!DOCTYPE dataset SYSTEM "database-schema.dtd">
<dataset>

	<Application path="path" name="My Application"/>

	<!-- Templates without attachments -->
	<Template template_id="1" handlerClassName="org.ldp4j.application.MyRDFSourceTemplate" name="MyRDFSourceTemplate" description="A RDF source template" app_path="path"/>
	<Template template_id="2" handlerClassName="org.ldp4j.application.MyBasicContainerTemplate" name="MyBasicContainerTemplate" description="A Basic Container Template" app_path="path"/>
	<Template template_id="3" handlerClassName="org.ldp4j.application.MyDirectContainerTemplate" name="MyDirectContainerTemplate" description="A Direct Container Template" app_path="path"/>
	<Template template_id="4" handlerClassName="org.ldp4j.application.MyIndirectContainerTemplate" name="MyIndirectContainerTemplate" description="An Indirect Container Template" app_path="path"/>

	<!-- Templates with attachments -->
	<Template template_id="51" handlerClassName="org.ldp4j.application.MyAttachingRDFSourceTemplate" name="MyAttachingRDFSourceTemplate" description="An RDF source template with Attachments" app_path="path"/>
	<Template template_id="52" handlerClassName="org.ldp4j.application.MyAttachingBasicContainerTemplate" name="MyAttachingBasicContainerTemplate" description="A Basic Container Template with Attachments" app_path="path"/>
	<Template template_id="53" handlerClassName="org.ldp4j.application.MyAttachingDirectContainerTemplate" name="MyAttachingDirectContainerTemplate" description="A Direct Container Template with Attachments" app_path="path"/>
	<Template template_id="54" handlerClassName="org.ldp4j.application.MyAttachingIndirectContainerTemplate" name="MyAttachingIndirectContainerTemplate" description="An Indirect Container Template with Attachments" app_path="path"/>

	<!-- Basic container templates -->
	<Template template_id="31" handlerClassName="org.ldp4j.application.bc.RDFSources" name="bc.RDFSources" description="Basic container of RDF sources" app_path="path"/>
	<Template template_id="32" handlerClassName="org.ldp4j.application.bc.BasicContainers" name="bc.BasicContainers" description="Basic container of Basic containers" app_path="path"/>
	<Template template_id="33" handlerClassName="org.ldp4j.application.bc.DirectContainers" name="bc.DirectContainers" description="Basic container of Direct containers" app_path="path"/>
	<Template template_id="34" handlerClassName="org.ldp4j.application.bc.IndirectContainers" name="bc.IndirectContainers" description="Basic container of Indirect containers" app_path="path"/>

	<TemplateAttachment attachment_id="1" name="RDFSource" path="rdf_source" owner_template_id="51" attached_template_id="1" />
	<TemplateAttachment attachment_id="2" name="BasicContainer" path="basic_container" owner_template_id="51" attached_template_id="2"/>
	<TemplateAttachment attachment_id="3" name="DirectContainer" path="direct_container" owner_template_id="51" attached_template_id="3"/>
	<TemplateAttachment attachment_id="4" name="IndirectContainer" path="indirect_container" owner_template_id="51" attached_template_id="4"/>

	<RDFSourceTemplate template_id="1" />
	<RDFSourceTemplate template_id="2" />
	<RDFSourceTemplate template_id="3" />
	<RDFSourceTemplate template_id="4" />

	<RDFSourceTemplate template_id="51" />
	<RDFSourceTemplate template_id="52" />
	<RDFSourceTemplate template_id="53" />
	<RDFSourceTemplate template_id="54" />

	<RDFSourceTemplate template_id="31" />
	<RDFSourceTemplate template_id="32" />
	<RDFSourceTemplate template_id="33" />
	<RDFSourceTemplate template_id="34" />

	<BasicContainerTemplate template_id="2" member_template_id="1" />
	<BasicContainerTemplate template_id="52" member_template_id="51" />

	<BasicContainerTemplate template_id="31" member_template_id="1" />
	<BasicContainerTemplate template_id="32" member_template_id="2" />
	<BasicContainerTemplate template_id="33" member_template_id="3" />
	<BasicContainerTemplate template_id="34" member_template_id="4" />

	<DirectContainerTemplate template_id="3" member_template_id="1"  membershipPredicate="http://www.ldp4j.org/vocab#hasMember" membershipRelation="HAS_MEMBER"/>
	<DirectContainerTemplate template_id="53" member_template_id="51"  membershipPredicate="http://www.ldp4j.org/vocab#hasMember" membershipRelation="HAS_MEMBER"/>

	<IndirectContainerTemplate template_id="4" member_template_id="1"  membershipPredicate="http://www.ldp4j.org/vocab#isMemberOf" membershipRelation="IS_MEMBER_OF" insertedContentRelation="http://www.ldp4j.org/vocab#id"/>
	<IndirectContainerTemplate template_id="54" member_template_id="51"  membershipPredicate="http://www.ldp4j.org/vocab#isMemberOf" membershipRelation="IS_MEMBER_OF" insertedContentRelation="http://www.ldp4j.org/vocab#id"/>

</dataset>

=== berezovskyi/ldp4j/framework/application/persistency/src/test/resources/deletable-application.xml
<!--

    #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
      This file is part of the LDP4j Project:
        http://www.ldp4j.org/

      Center for Open Middleware
        http://www.centeropenmiddleware.com/
    #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
      Copyright (C) 2014 Center for Open Middleware.
    #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
      Licensed under the Apache License, Version 2.0 (the "License");
      you may not use this file except in compliance with the License.
      You may obtain a copy of the License at

                http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.
    #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
      Artifact    : org.ldp4j.framework:ldp4j-application-persistency:1.0.0-SNAPSHOT
      Bundle      : ldp4j-application-persistency-1.0.0-SNAPSHOT.jar
    #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#

-->
<!DOCTYPE dataset SYSTEM "database-schema.dtd">
<dataset>

	<Application path="deletable_path" name="My Deleteable Application"/>

	<!-- Templates without attachments -->
	<Template template_id="10001" handlerClassName="org.ldp4j.application.MyRDFSourceTemplate" name="MyRDFSourceTemplate" description="A RDF source template" app_path="deletable_path"/>
	<Template template_id="10002" handlerClassName="org.ldp4j.application.MyBasicContainerTemplate" name="MyBasicContainerTemplate" description="A Basic Container Template" app_path="deletable_path"/>
	<Template template_id="10003" handlerClassName="org.ldp4j.application.MyDirectContainerTemplate" name="MyDirectContainerTemplate" description="A Direct Container Template" app_path="deletable_path"/>
	<Template template_id="10004" handlerClassName="org.ldp4j.application.MyIndirectContainerTemplate" name="MyIndirectContainerTemplate" description="An Indirect Container Template" app_path="deletable_path"/>

	<!-- Templates with attachments -->
	<Template template_id="100051" handlerClassName="org.ldp4j.application.MyAttachingRDFSourceTemplate" name="MyAttachingRDFSourceTemplate" description="An RDF source template with Attachments" app_path="deletable_path"/>
	<Template template_id="100052" handlerClassName="org.ldp4j.application.MyAttachingBasicContainerTemplate" name="MyAttachingBasicContainerTemplate" description="A Basic Container Template with Attachments" app_path="deletable_path"/>
	<Template template_id="100053" handlerClassName="org.ldp4j.application.MyAttachingDirectContainerTemplate" name="MyAttachingDirectContainerTemplate" description="A Direct Container Template with Attachments" app_path="deletable_path"/>
	<Template template_id="100054" handlerClassName="org.ldp4j.application.MyAttachingIndirectContainerTemplate" name="MyAttachingIndirectContainerTemplate" description="An Indirect Container Template with Attachments" app_path="deletable_path"/>

	<TemplateAttachment attachment_id="10001" name="RDFSource" path="rdf_source" owner_template_id="100051" attached_template_id="10001" />
	<TemplateAttachment attachment_id="10002" name="BasicContainer" path="basic_container" owner_template_id="100051" attached_template_id="10002"/>
	<TemplateAttachment attachment_id="10003" name="DirectContainer" path="direct_container" owner_template_id="100051" attached_template_id="10003"/>
	<TemplateAttachment attachment_id="10004" name="IndirectContainer" path="indirect_container" owner_template_id="100051" attached_template_id="10004"/>

	<RDFSourceTemplate template_id="10001" />
	<RDFSourceTemplate template_id="10002" />
	<RDFSourceTemplate template_id="10003" />
	<RDFSourceTemplate template_id="10004" />

	<RDFSourceTemplate template_id="100051" />
	<RDFSourceTemplate template_id="100052" />
	<RDFSourceTemplate template_id="100053" />
	<RDFSourceTemplate template_id="100054" />

	<BasicContainerTemplate template_id="10002" member_template_id="10001" />
	<BasicContainerTemplate template_id="100052" member_template_id="100051" />

	<DirectContainerTemplate template_id="10003" member_template_id="10001"  membershipPredicate="http://www.ldp4j.org/vocab#hasMember" membershipRelation="HAS_MEMBER"/>
	<DirectContainerTemplate template_id="100053" member_template_id="100051"  membershipPredicate="http://www.ldp4j.org/vocab#hasMember" membershipRelation="HAS_MEMBER"/>

	<IndirectContainerTemplate template_id="10004" member_template_id="10001"  membershipPredicate="http://www.ldp4j.org/vocab#isMemberOf" membershipRelation="IS_MEMBER_OF" insertedContentRelation="http://www.ldp4j.org/vocab#id"/>
	<IndirectContainerTemplate template_id="100054" member_template_id="100051"  membershipPredicate="http://www.ldp4j.org/vocab#isMemberOf" membershipRelation="IS_MEMBER_OF" insertedContentRelation="http://www.ldp4j.org/vocab#id"/>

</dataset>

=== berezovskyi/ldp4j/framework/application/persistency/src/test/resources/custom-root-resources.xml
<!--

    #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
      This file is part of the LDP4j Project:
        http://www.ldp4j.org/

      Center for Open Middleware
        http://www.centeropenmiddleware.com/
    #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
      Copyright (C) 2014 Center for Open Middleware.
    #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
      Licensed under the Apache License, Version 2.0 (the "License");
      you may not use this file except in compliance with the License.
      You may obtain a copy of the License at

                http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.
    #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
      Artifact    : org.ldp4j.framework:ldp4j-application-persistency:1.0.0-SNAPSHOT
      Bundle      : ldp4j-application-persistency-1.0.0-SNAPSHOT.jar
    #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#

-->
<!DOCTYPE dataset SYSTEM "database-schema.dtd">
<dataset>
	<Endpoint endpoint_id="2" path="/container/" created="2012-03-14" entityTag="etag" modified="2012-03-14" app_path="path"/>

	<Endpoint endpoint_id="31" path="/basic_container/rdf_source/" created="2012-03-14" entityTag="etag" modified="2012-03-14" app_path="path"/>
	<Endpoint endpoint_id="32" path="/basic_container/basic_container/" created="2012-03-14" entityTag="etag" modified="2012-03-14" app_path="path"/>
	<Endpoint endpoint_id="33" path="/basic_container/direct_container/" created="2012-03-14" entityTag="etag" modified="2012-03-14" app_path="path"/>
	<Endpoint endpoint_id="34" path="/basic_container/indirect_container/" created="2012-03-14" entityTag="etag" modified="2012-03-14" app_path="path"/>

	<Resource resource_id="2" businessKey="containerKey" template_id="2" endpoint_id="2"/>

	<Resource resource_id="31" businessKey="bcRSKey" template_id="31" endpoint_id="31"/>
	<Resource resource_id="32" businessKey="bcBCKey" template_id="32" endpoint_id="32"/>
	<Resource resource_id="33" businessKey="bcDCKey" template_id="33" endpoint_id="33"/>
	<Resource resource_id="34" businessKey="bcICKey" template_id="34" endpoint_id="34"/>

	<RDFSource resource_id="2"/>

	<RDFSource resource_id="31"/>
	<RDFSource resource_id="32"/>
	<RDFSource resource_id="33"/>
	<RDFSource resource_id="34"/>

	<Container resource_id="2" memberCount="0"/>

	<Container resource_id="31" memberCount="0"/>
	<Container resource_id="32" memberCount="0"/>
	<Container resource_id="33" memberCount="0"/>
	<Container resource_id="34" memberCount="0"/>

	<Slug resource_id="2" path="slug" version="23"/>
	<Slug resource_id="2" path="slug_23" version="24"/>
</dataset>
